export const INVOICE_THEMES = {
  classicPurple: {
    id: 'classicPurple',
    name: 'Classic Purple',
    description: 'Traditional deep purple invoice design',
    primaryColor: '#4338CA',
    secondaryColor: '#312E81',
    accentColor: '#F59E0B',
    borderColor: '#C7CBD9',
    textColor: '#1F2937',
    headerBackground: 'linear-gradient(135deg, #4338CA, #312E81)',
    headerBg: '#4338CA',
    totalBackground: '#312E81',
    tableHeaderBg: '#4338CA',
    tableHeaderColor: '#FFFFFF',
    tableAltRow: '#F8FAFF',
    tableSubHeader: '#EEF2FF',
    tableSubHeaderColor: '#312E81',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    borderStyle: 'thin',
    accentBorder: '#F59E0B',
    grandTotalBg: '#312E81',
    grandTotalColor: '#FFFFFF',
    goldTint: '#FFFBEB',
    goldTintColor: '#78350F',
    summaryLabelColor: '#374151',
    summaryValueColor: '#1F2937',
    footerBg: '#EEF2FF',
    footerBorderColor: '#F59E0B',
    signatoryColor: '#4338CA',
    amountWordsBg: '#FFFBEB',
    amountWordsBorder: '#F59E0B',
    taglineColor: '#F59E0B',
    addressColor: '#E0E7FF',
    gstinColor: '#FFFFFF',
    logoFrameBg: '#FFFFFF',
    bodyBg: '#FFFFFF'
  },
  premiumGold: {
    id: 'premiumGold',
    name: 'Premium Gold',
    description: 'Elegant dark neutral with gold accents',
    primaryColor: '#1C1917',
    secondaryColor: '#292524',
    accentColor: '#D97706',
    borderColor: '#D6D3D1',
    textColor: '#1C1917',
    headerBackground: 'linear-gradient(135deg, #1C1917, #292524)',
    headerBg: '#1C1917',
    totalBackground: '#292524',
    tableHeaderBg: '#1C1917',
    tableHeaderColor: '#FEF3C7',
    tableAltRow: '#FFFBEB',
    tableSubHeader: '#FEF3C7',
    tableSubHeaderColor: '#78350F',
    fontFamily: 'Georgia, "Times New Roman", serif',
    borderStyle: 'medium',
    accentBorder: '#D97706',
    grandTotalBg: '#292524',
    grandTotalColor: '#FEF3C7',
    goldTint: '#FEF3C7',
    goldTintColor: '#78350F',
    summaryLabelColor: '#44403C',
    summaryValueColor: '#1C1917',
    footerBg: '#FEF3C7',
    footerBorderColor: '#D97706',
    signatoryColor: '#92400E',
    amountWordsBg: '#FEF3C7',
    amountWordsBorder: '#D97706',
    taglineColor: '#D97706',
    addressColor: '#D6D3D1',
    gstinColor: '#FEF3C7',
    logoFrameBg: '#FEF3C7',
    bodyBg: '#FFFFFF'
  },
  modernBlue: {
    id: 'modernBlue',
    name: 'Modern Blue',
    description: 'Clean corporate blue design',
    primaryColor: '#2563EB',
    secondaryColor: '#1D4ED8',
    accentColor: '#0EA5E9',
    borderColor: '#BFDBFE',
    textColor: '#1E293B',
    headerBackground: 'linear-gradient(135deg, #2563EB, #1D4ED8)',
    headerBg: '#2563EB',
    totalBackground: '#1D4ED8',
    tableHeaderBg: '#2563EB',
    tableHeaderColor: '#FFFFFF',
    tableAltRow: '#F0F9FF',
    tableSubHeader: '#DBEAFE',
    tableSubHeaderColor: '#1E3A8A',
    fontFamily: '"Segoe UI", Roboto, "Helvetica Neue", sans-serif',
    borderStyle: 'thin',
    accentBorder: '#0EA5E9',
    grandTotalBg: '#1D4ED8',
    grandTotalColor: '#FFFFFF',
    goldTint: '#F0F9FF',
    goldTintColor: '#0C4A6E',
    summaryLabelColor: '#334155',
    summaryValueColor: '#1E293B',
    footerBg: '#DBEAFE',
    footerBorderColor: '#0EA5E9',
    signatoryColor: '#2563EB',
    amountWordsBg: '#F0F9FF',
    amountWordsBorder: '#0EA5E9',
    taglineColor: '#0EA5E9',
    addressColor: '#93C5FD',
    gstinColor: '#FFFFFF',
    logoFrameBg: '#FFFFFF',
    bodyBg: '#FFFFFF'
  },
  luxuryDark: {
    id: 'luxuryDark',
    name: 'Luxury Dark',
    description: 'Premium dark header with elegant appearance',
    primaryColor: '#111827',
    secondaryColor: '#1F2937',
    accentColor: '#A78BFA',
    borderColor: '#374151',
    textColor: '#1F2937',
    headerBackground: 'linear-gradient(135deg, #111827, #1F2937)',
    headerBg: '#111827',
    totalBackground: '#1F2937',
    tableHeaderBg: '#111827',
    tableHeaderColor: '#E5E7EB',
    tableAltRow: '#F9FAFB',
    tableSubHeader: '#E5E7EB',
    tableSubHeaderColor: '#1F2937',
    fontFamily: '"Trebuchet MS", "Lucida Sans", sans-serif',
    borderStyle: 'medium',
    accentBorder: '#A78BFA',
    grandTotalBg: '#111827',
    grandTotalColor: '#E5E7EB',
    goldTint: '#F5F3FF',
    goldTintColor: '#5B21B6',
    summaryLabelColor: '#6B7280',
    summaryValueColor: '#1F2937',
    footerBg: '#F3F4F6',
    footerBorderColor: '#A78BFA',
    signatoryColor: '#7C3AED',
    amountWordsBg: '#F5F3FF',
    amountWordsBorder: '#A78BFA',
    taglineColor: '#A78BFA',
    addressColor: '#9CA3AF',
    gstinColor: '#E5E7EB',
    logoFrameBg: '#374151',
    bodyBg: '#FFFFFF'
  },
  minimal: {
    id: 'minimal',
    name: 'Minimal',
    description: 'Very clean white design with minimal borders',
    primaryColor: '#374151',
    secondaryColor: '#4B5563',
    accentColor: '#6B7280',
    borderColor: '#E5E7EB',
    textColor: '#111827',
    headerBackground: 'linear-gradient(135deg, #F9FAFB, #F3F4F6)',
    headerBg: '#F9FAFB',
    totalBackground: '#111827',
    tableHeaderBg: '#F3F4F6',
    tableHeaderColor: '#374151',
    tableAltRow: '#FAFAFA',
    tableSubHeader: '#F9FAFB',
    tableSubHeaderColor: '#6B7280',
    fontFamily: '"Helvetica Neue", Arial, sans-serif',
    borderStyle: 'hairline',
    accentBorder: '#D1D5DB',
    grandTotalBg: '#111827',
    grandTotalColor: '#F9FAFB',
    goldTint: '#F9FAFB',
    goldTintColor: '#374151',
    summaryLabelColor: '#6B7280',
    summaryValueColor: '#111827',
    footerBg: '#F9FAFB',
    footerBorderColor: '#D1D5DB',
    signatoryColor: '#374151',
    amountWordsBg: '#F9FAFB',
    amountWordsBorder: '#D1D5DB',
    taglineColor: '#6B7280',
    addressColor: '#9CA3AF',
    gstinColor: '#6B7280',
    logoFrameBg: '#F3F4F6',
    bodyBg: '#FFFFFF'
  },
  resortGreen: {
    id: 'resortGreen',
    name: 'Resort Green',
    description: 'Natural resort-style green accent',
    primaryColor: '#047857',
    secondaryColor: '#065F46',
    accentColor: '#10B981',
    borderColor: '#A7F3D0',
    textColor: '#064E3B',
    headerBackground: 'linear-gradient(135deg, #047857, #065F46)',
    headerBg: '#047857',
    totalBackground: '#065F46',
    tableHeaderBg: '#047857',
    tableHeaderColor: '#ECFDF5',
    tableAltRow: '#ECFDF5',
    tableSubHeader: '#D1FAE5',
    tableSubHeaderColor: '#065F46',
    fontFamily: '"Trebuchet MS", Verdana, sans-serif',
    borderStyle: 'thin',
    accentBorder: '#10B981',
    grandTotalBg: '#065F46',
    grandTotalColor: '#ECFDF5',
    goldTint: '#ECFDF5',
    goldTintColor: '#065F46',
    summaryLabelColor: '#374151',
    summaryValueColor: '#064E3B',
    footerBg: '#D1FAE5',
    footerBorderColor: '#10B981',
    signatoryColor: '#047857',
    amountWordsBg: '#ECFDF5',
    amountWordsBorder: '#10B981',
    taglineColor: '#10B981',
    addressColor: '#6EE7B7',
    gstinColor: '#ECFDF5',
    logoFrameBg: '#FFFFFF',
    bodyBg: '#FFFFFF'
  }
};

export function getTheme(themeId) {
  return INVOICE_THEMES[themeId] || INVOICE_THEMES.classicPurple;
}

export function getThemeList() {
  return Object.values(INVOICE_THEMES);
}
